name: Multi-Armed Bandit

on:
  schedule:
    - cron: '1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    environment: SSE
    steps:
      - uses: actions/checkout@v2
      - name: Multi-Armed Bandit in Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          cache: 'npm'
      - run: npm install
      - name: Run App
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CLIENT_SDK_KEY: ${{ secrets.CLIENT_SDK_KEY }}
          SDK_KEY: ${{ secrets.SDK_KEY }}
          FLAG: trial-duration
          PROJECT: support-service
          ENV: rneal
          METRIC_KEY: started-registration
          PORT: 8087
        run: node app